'use server';

/**
 * @fileOverview Generates actionable signals (BET/NO_BET/WAIT) based on the Fair Probability Envelope and market data.
 *
 * - generateActionableSignal - A function that generates the actionable signal.
 * - ActionableSignalInput - The input type for the generateActionableSignal function.
 * - ActionableSignalOutput - The return type for the generateActionableSignal function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ActionableSignalInputSchema = z.object({
  fairProbabilityEnvelopeLower: z
    .number()
    .describe('The lower bound of the fair probability envelope.'),
  fairProbabilityEnvelopeUpper: z
    .number()
    .describe('The upper bound of the fair probability envelope.'),
  currentMarketPrice: z
    .number()
    .describe('The current market price of the contract.'),
  marketSentiment: z.string().describe('The current market sentiment.'),
  liquidity: z.number().describe('Liquidity of the market.'),
});
export type ActionableSignalInput = z.infer<typeof ActionableSignalInputSchema>;

const ActionableSignalOutputSchema = z.object({
  signal: z
    .enum(['BET', 'NO_BET', 'WAIT'])
    .describe('The actionable signal generated by the AI.'),
  reason: z
    .string()
    .describe('The reasoning behind the generated actionable signal.'),
});
export type ActionableSignalOutput = z.infer<typeof ActionableSignalOutputSchema>;

export async function generateActionableSignal(
  input: ActionableSignalInput
): Promise<ActionableSignalOutput> {
  return actionableSignalFlow(input);
}

const actionableSignalPrompt = ai.definePrompt({
  name: 'actionableSignalPrompt',
  input: {schema: ActionableSignalInputSchema},
  output: {schema: ActionableSignalOutputSchema},
  prompt: `You are an AI assistant that generates actionable signals for prediction markets.
  Based on the fair probability envelope (lower bound: {{{fairProbabilityEnvelopeLower}}}, upper bound: {{{fairProbabilityEnvelopeUpper}}}) and the current market price ({{{currentMarketPrice}}}), as well as market sentiment ({{{marketSentiment}}}) and liquidity ({{{liquidity}}}), determine whether to BET, NO_BET, or WAIT.

  Provide a brief reason for your signal.

  Here's how to determine the signal:
  - If the current market price is significantly below the fair probability envelope, then BET.
  - If the current market price is significantly above the fair probability envelope, then NO_BET.
  - If the current market price is within the fair probability envelope, or there is not enough liquidity, then WAIT.

  Return the signal and the reasoning.
`,
});

const actionableSignalFlow = ai.defineFlow(
  {
    name: 'actionableSignalFlow',
    inputSchema: ActionableSignalInputSchema,
    outputSchema: ActionableSignalOutputSchema,
  },
  async input => {
    const {output} = await actionableSignalPrompt(input);
    return output!;
  }
);
